package com.atguigu.mbg.entities;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.name
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.id
     *
     * @return the value of departments.id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.id
     *
     * @param id the value for departments.id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.name
     *
     * @return the value of departments.name
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.name
     *
     * @param name the value for departments.name
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}