package com.atguigu.mbg.entities;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.last_name
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.email
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.salary
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.dept_id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.last_name
     *
     * @return the value of employees.last_name
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.last_name
     *
     * @param lastName the value for employees.last_name
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.email
     *
     * @return the value of employees.email
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.email
     *
     * @param email the value for employees.email
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.salary
     *
     * @return the value of employees.salary
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.salary
     *
     * @param salary the value for employees.salary
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.dept_id
     *
     * @return the value of employees.dept_id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.dept_id
     *
     * @param deptId the value for employees.dept_id
     *
     * @mbggenerated Mon Jan 15 16:42:00 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

	@Override
	public String toString() {
		return "Employee [id=" + id + ", lastName=" + lastName + ", email=" + email + ", salary=" + salary + ", deptId="
				+ deptId + "]";
	}
    
    
}